services:
  web:
    build: .
    container_name: web-app
    ports:
      - "5001:5001"
    volumes:
      - .:/app
  #   depends_on:
  #     - db
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword